### ISSUE TITLE
Konsole icon is invisible in window decorations

### ISSUE THREAD

**Issue by davidedmundson** [NitruxSA/plasma-next-icons#29] opened 2015-01-09 12:23 UTC
https://bugs.kde.org/show_bug.cgi?id=342657

**Comment by UriHerrera** [comment] 2015-01-09 19:44
That bug should be a duplicate of [this](https://bugs.kde.org/show_bug.cgi?id=337666) as it's because of the same reasons.

**Closed** 2015-01-23 23:10 UTC
Labels: duplicate
