### ISSUE TITLE
Breeze in LibreOffice

### ISSUE THREAD

**Issue by philipzae** [NitruxSA/plasma-next-icons#6] opened 2014-11-03 06:08 UTC
It would be great to be able to have the new breeze icon theme in libreoffice. Below is an initial list of icons that are found in libreoffice's main two toolbars.

Standard Toolbar - New, Open, Save, Save As, Attach Document to Email, Edit Document, Export to PDF, Print, Print Directly, Print Preview, Cut, Copy, Paste, Format Paintbrush, Spellcheck, Automatic Spell Checking, Find, Find & Replace, Non-Printable Character, Table, Image, Chart, Footnote, Page Break, Hyperlink, Symbol, Page Number, Comment, Textbox, Shapes, Data Sources, Help

Formatting Toolbar - Styles, Bold, Italics, Underline, Strike Through, Shadow, Font Outline, Increase Font, Decrease Font, Superscript, Subscript, Font Color, Highlight Color, Background Color, Numbering List, Bullet List, Increase Indent, Decrease Indent, Left Alignment, Center Alignment, Right Alignment, Justified, Line Spacing 1, Line Spacing 1.5, Line Spacing 2, Right to Left, Left to Right, Select All

**Comment by DarkknightAK** [comment] 2015-02-02 21:46
Hi I start to look at each toolbar in the LO apps and make the icons. they are ordinary located in the cmd folder but some icons are in other folders like:
![Formula](https://dl.dropboxusercontent.com/u/1642456/vdg/plasma-next-icons-working/action/toolbar/LO/writerFormula-b.png)
icon lc20556 from the sw folder, but there is a lc_insertformula icon in cmd
![writer search toolbar](https://dl.dropboxusercontent.com/u/1642456/vdg/plasma-next-icons-working/action/toolbar/LO/writerSearch-b.png)

what can we do? I would prefere to have the icons with the right naming in the right folder. and links to the used icons. about the links. there are two opportunities:
1. write the links into the link.txt file
2. make links to the folder like we do it in the repository right now. than we don't need the link.txt file. The problem is we now look at the LO/cmd lc_ files, but there are more folders. so should we sort the git repository like the LO icon folder structure or can we reduce the folder structure, because there are a lot of folders with strange icon names like av02051, da01, ...

**Comment by philipzae** [comment] 2015-02-08 03:28
Duplicate icons are written into the link.txt file so there isnt a need to duplicate the file in the git repo.

**Comment by DarkknightAK** [comment] 2015-02-08 12:08
OK. What is about the other folders excluding cmd why have some icons no real names.

**Comment by DarkknightAK** [comment] 2015-02-13 23:54
Hi,

sizes
- lc_ icons 24x24px are used when you select large icons in the settings 
- sc_ icons 16x16px are used when you select small icons in the settings
the menue bar use always the sc_ icons

folders
- cmd is used for most icons there are over 1.500 icons (don't like it)

my wish is to rename the LO_lc_icons_breeze folder into LO and make there (for the first) two folders small and large (maybe some special folders we will see) in the folder there are the lc_ and sc_ files without lc_ and sc_ prefix.

that you can use the LO theme I will link the LO files with our grouping with the link.txt file.

**Comment by philipzae** [comment] 2015-02-16 04:49
I havent been around long enough to know the reasoning for the other folders outside of cmd or why the icons in those folders dont have useful file names.

Regarding the icons sizes, lc_ icons are for icons used when a user sets his icons to large. For most icon sets, lc_ is 24x24, while with the galaxy icon set they are 26x26. sc_ icons are used when a user sets his icons to small and the icons are 16x16 and the icons also appear in the menu bar in windows and linux.

Uri has been making 18x18 svgs which i have been creating 24x24 lc_ pngs by adding 3 pixels of padding on all sides and including it in the LO git repo. If 16x16 icons are not possible to be created, then my intent was to create 18x18 pngs for use in the toolbars and the menu bar will likely shrink them to fit the 16x16 space provided.

**Comment by DarkknightAK** [comment] 2015-02-16 08:10
thanks for the feedback. 

As you can see in the repository the lc files are "nearly" finished (75 %). I'd like to start with the sc_ files. About the file size there are two possibilities:
1. 16x16px
2. 18x18px
the icons are 12x12px in size with an 2px or 3 px padding. what do you think?

in addition I'd like to make 2 dictionaries in the git folder LO one smal and one large. for special icons like the calc diagram icons I will see but maybe I make additional folders.

**Comment by philipzae** [comment] 2015-02-17 19:09
The sc_ files need to be 16x16px in order for them to appear clear in the menus. Where are getting these 12x12px icons?

**Comment by DarkknightAK** [comment] 2015-02-17 20:57
12x12px was a mistake. This is the icon size without padding. ok I'll make the sc_ files 16x16px.

**Comment by philipzae** [comment] 2015-02-20 14:15
Yes where are you getting the 12x12px icons without padding?

**Comment by UriHerrera** [comment] 2015-04-08 02:16
Since @DarkknightAK has completed the icons for LibreOffice I'm tagging this as fix released and closing the issue.

**Closed by UriHerrera** 2015-04-08 02:16 UTC
Labels: fix-released
