### ISSUE TITLE
Inconsistent icons

### ISSUE THREAD

**Issue by m1ga** [NitruxSA/plasma-next-icons#157] opened 2015-05-31 14:32 UTC
just some "usage" feedback:

![icons](http://migaweb.de/icons.jpg)

While the firefox icon is the same in the titlebar, taskbar and taskswitcher the konsole icon is different. The small icon just has an outline and >_ instead of just >
I find myself often search for konsole in the my open window list because of the icons isn't that recognizable with the small outline and I search for the black version (I know when I make the taskbar higher it will change to the black icon)

**Comment by UriHerrera** [comment] 2015-06-02 15:33
Duplicate of: https://github.com/NitruxSA/plasma-next-icons/issues/29

**Closed by UriHerrera** 2015-06-02 15:33 UTC

**Comment by m1ga** [comment] 2015-06-02 19:32
ok, i understand that, but its still different. The monochrome icon is not just the monochrome version of the big one. It even has more features than the big version. Shouldn't the big colored icon have the _ too?

**Comment by UriHerrera** [comment] 2015-06-02 20:45
No. They're for different things.
